#!/usr/bin/env sh

set -e

if output=$(git status --porcelain) && [ -z "$output" ]; then
  echo 'Releasing 🚀'

  echo '\nChecking out the Master branch...'
  git checkout master
  git pull

  echo '\nBuilding docs...'
  yarn deploy-storybook

  echo '\nBuilding release...'
  yarn build

  echo '\nPublishing...'
  yarn config set version-tag-prefix "release/"
  yarn config set version-git-message "[release][ci skip] prepare release/%s"
  yarn version
  version=$(node -e "console.log(require('./package.json').version)")
  yarn publish --new-version $version

  echo '\nPushing the new tag...'
  git push origin master
  git push origin "release/$version"

  echo '\nBravo 👏'
else
  echo '☠️  Uncommitted Files: Please commit all files first.'
  exit 1
fi
